baseurl = "http://www.vkng.me"
languageCode = "en-us"
title = "Viking [in Training]"

[author]
  name = "David Tomberlin"

  [taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[params]
    # You can use markdown here.
    brand = "Viking"
    topline = "Software Dev, Gamer, Lifter"
    footline = ""

    # Sidebar position
    # false, true, "left", "right"
    sidebar = "left"
